[package]
name = "diesel_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.11", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "serde_json"] }
dotenvy = "0.15.7"
